version: '3.8'
services:
  alma8:
    image: perfsonar/unibuild-alma8:latest
    volumes:
      -  .:/app
  centos7:
    image: perfsonar/unibuild-centos7:latest
    network_mode: "host"
    volumes:
      - .:/app
  debian10:
    image: perfsonar/unibuild-debian10:latest
    volumes:
      -  .:/app
